nome = input("Digite seu nome completo: ").strip().title()
nome = nome.split()
print("Prazer em te conhecer!")
print(f"Seu primeiro nome é {nome[0]}")
print(f"Seu primeiro nome é {nome[len(nome)-1]}")